// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/grpctest.proto

/*
Package grpctest is a generated protocol buffer package.

It is generated from these files:
	proto/grpctest.proto

It has these top-level messages:
	MathReq
	MathResp
*/
package grpctest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MathReq struct {
	N1 int32 `protobuf:"varint,1,opt,name=N1" json:"N1,omitempty"`
	N2 int32 `protobuf:"varint,2,opt,name=N2" json:"N2,omitempty"`
}

func (m *MathReq) Reset()                    { *m = MathReq{} }
func (m *MathReq) String() string            { return proto.CompactTextString(m) }
func (*MathReq) ProtoMessage()               {}
func (*MathReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MathReq) GetN1() int32 {
	if m != nil {
		return m.N1
	}
	return 0
}

func (m *MathReq) GetN2() int32 {
	if m != nil {
		return m.N2
	}
	return 0
}

type MathResp struct {
	Sum int32 `protobuf:"varint,1,opt,name=Sum" json:"Sum,omitempty"`
}

func (m *MathResp) Reset()                    { *m = MathResp{} }
func (m *MathResp) String() string            { return proto.CompactTextString(m) }
func (*MathResp) ProtoMessage()               {}
func (*MathResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MathResp) GetSum() int32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*MathReq)(nil), "grpctest.MathReq")
	proto.RegisterType((*MathResp)(nil), "grpctest.MathResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Math service

type MathClient interface {
	Sum(ctx context.Context, in *MathReq, opts ...grpc.CallOption) (*MathResp, error)
}

type mathClient struct {
	cc *grpc.ClientConn
}

func NewMathClient(cc *grpc.ClientConn) MathClient {
	return &mathClient{cc}
}

func (c *mathClient) Sum(ctx context.Context, in *MathReq, opts ...grpc.CallOption) (*MathResp, error) {
	out := new(MathResp)
	err := grpc.Invoke(ctx, "/grpctest.Math/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Math service

type MathServer interface {
	Sum(context.Context, *MathReq) (*MathResp, error)
}

func RegisterMathServer(s *grpc.Server, srv MathServer) {
	s.RegisterService(&_Math_serviceDesc, srv)
}

func _Math_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctest.Math/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServer).Sum(ctx, req.(*MathReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Math_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpctest.Math",
	HandlerType: (*MathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Math_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/grpctest.proto",
}

func init() { proto.RegisterFile("proto/grpctest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2f, 0x2a, 0x48, 0x2e, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x73, 0x85, 0x38, 0x60,
	0x7c, 0x25, 0x4d, 0x2e, 0x76, 0xdf, 0xc4, 0x92, 0x8c, 0xa0, 0xd4, 0x42, 0x21, 0x3e, 0x2e, 0x26,
	0x3f, 0x43, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x26, 0x3f, 0x43, 0x30, 0xdf, 0x48, 0x82,
	0x09, 0xca, 0x37, 0x52, 0x92, 0xe1, 0xe2, 0x80, 0x28, 0x2d, 0x2e, 0x10, 0x12, 0xe0, 0x62, 0x0e,
	0x2e, 0xcd, 0x85, 0x2a, 0x06, 0x31, 0x8d, 0xcc, 0xb8, 0x58, 0x40, 0xb2, 0x42, 0x7a, 0x60, 0x19,
	0x21, 0x41, 0x3d, 0xb8, 0x95, 0x50, 0xf3, 0xa5, 0x84, 0xd0, 0x85, 0x8a, 0x0b, 0x94, 0x18, 0x92,
	0xd8, 0xc0, 0x2e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x91, 0x24, 0x0e, 0xa9, 0x00,
	0x00, 0x00,
}
